sudo: required
services:
  - docker

before_install:
  - docker build -t jicamon/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jicamon/docker-react npm run test
  
language: generic
